### ISSUE TITLE
Is this module production ready? 

### ISSUE THREAD

**Issue by sandipp** [kayomarz/dynamodb-data-types#3]
Thanks for nice work. 
I have question that is this module safe to use in production?
As I can see you not maintaing it from last year.
Please Update.

**Comment by jagadeeshops** [comment]
I am using this module to remove datatypes from the Dynamodb output. its processing B, S, SS, N and M. If any other data type is used other than the things mentioned in the module, it will give unsupported datatype error.If you are sure that your dynamodb will have the datatypes supported by this module, yo can go ahead and use it for removing datatypes. I didnt tested adding data types to json.

**Comment by kayomarz** [comment]
Thank you @jagadeeshops and @sandipp.

**dynamodb-data-types** was written during *AWS SDK ver 1.x*. At that time, AWS SDK did not include data types `BOOL`, `L`, `M` and `NULL` (If I remember correctly)

I will update **dynamodb-data-types** to handle these types. @jagadeeshops thanks for pointing it out and for the pull request.

Following are some points for the current *dynamodb-data-types* ver **0.2.7**:
  + *dynamodb-data-types* works fine with `N`, `NS`, `S`, `SS`
  + *dynamodb-data-types* does not work with `B`, `BS`  when used with *AWS SDK ver* **1.x**
  + *dynamodb-data-types* should work with `B`, `BS` when used with *AWS SDK ver* **2.x**. This is because *AWS SDK ver 2.x* announced automatic conversion of base64 [See AWS Upgrading Notes (1.x to 2.0)](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/upgrading.html).   

I will release a new version of *dynamodb-data-types* to incorporate the other data types within the next 3 to 4 days.

**Comment by kayomarz** [comment]
@jagadeeshops @sandipp I've made updated dynamodb-data-types to version 2.0.0. It supports all AttributeValue types namely BOOL, B, BS, L, M, N, NS, NULL, S, SS.

btw, AttributeValue.js has major changes. I've run the test suite on them but incase you encounter any issues, please open a new issue on github. Thanks.

**Comment by sandipp** [comment]
Thanks for updates, closing this issue now.

**Comment by fredrikslattman** [comment]
I have one issue where I need to store an array of strings in a given order. Example: ['b', 'c', 'a'] defined as SS will probably be stored as ['a', 'b', 'c']. Is this possible to prevent this? So I can choose the actual datatype for lists if needed?

**Comment by jagadeeshops** [comment]
This module wont change the order of elements in a array. this helps to answer the first part of your question. I didn't get the second part.please elaborate.

**Comment by brigand** [comment]
@fredrikslattman a Set (in dynamodb or otherwise) is unordered.  Dynamo gives you string and binary types for variable length ordered data, e.g. while inefficient you could base64 encode your items and join them with spaces, and store it in a string field.  You can then split and decode when pulling it back out.

For numbers, you can write them to a buffer in your desired type (uint32, float64, whatever), and put that in a B.

If you need ordered lists with atomic insert/splice/update operations, you have to use multiple rows or a conditional writes.

**Comment by kayomarz** [comment]
@fredrikslattman This library doesn't provide a way to explicitly specify the datatype for lists/values. See https://github.com/kayomarz/dynamodb-data-types#use-of-l-for-arrays to understand how datatype for arrays/sets is determined.

It would be useful if you can you describe the situation where you want to choose the actual datatype.

**Comment by fredrikslattman** [comment]
To give one quick example: A list with duplicate strings was the first issue we encountered - nothing major and is of course solvable in application logic instead. The datatype chosen was SS which removed the duplicate (in dDB) - datatype L doesn't behave the same.

Your answers has been good! I'll be start working with this module - if I find room for improvements I'll submit a PR!

**Comment by lpetre** [comment]
The Set types are unordered and unique, so the two cases where I want to force L instead of NS/SS/BS:
 - order is important
 - I have duplicate entries in my javascript array

My specific usage is an ordered list of strings, and I cannot let it become SS.

**Comment by kayomarz** [comment]
@lpetre thanks for mentioning your specific usage.  To make an example of what you're saying:

    data = {
      name: 'foo',
      colors: ['red', 'green', 'red'],
      friendsByAge: ['Jack', 'Jill', 'Jack']
    }

Lets say that for `colors` we don't care about duplicates but in `friendsByAge`, the order and duplicates should be maintained.

Here's one way we could modify the `wrap` call to allow forcing type `L` by using an options argument specifying fields which need to be forced to `L`

    wrap(data, {forceL: ['friendsByAge']});

This means that for nested data, any property named `friendsByAge` would be forced to use type `L`

Does this sound fine? Let me know if anyone has suggestions or other use cases / similar requirements

I will add it the API or if anyone has implemented a solution, do send a pull request.

**Comment by brigand** [comment]
I'd prefer:

```js
wrap(data, {
  types: {
    friendsByAge: 'L'
  }
});
```

Where the algorithm is:

 - let `types = {}`
 - for k,v in data: `types[k] = inferType(v)`
 - for k,v in options.types: `types[k] = options.types[k]`

This is simple to understand and can be expanded in the future.  You can throw an error if the type conversion can't be performed (indicates programmer mistake and/or validation error).

**Comment by kayomarz** [comment]
@brigand I agree. `{types: { friendsByAge: 'L' }}` is a good suggestion.

**Comment by petemill** [comment]
This is closed, but was the ability to force an array of strings to the List data-type implemented?

**Comment by kayomarz** [comment]
Not yet - I'll try to complete it over the weekend.

**Comment by kayomarz** [comment]
> This is closed, but was the ability to force an array of strings to the List data-type implemented?
@petemill This has now been implemented.

I'm locking this thread since the original topic is different, please start another issue thread if needed - Thanks~

**Comment by kayomarz** [comment]
@brigand, I've implemented this as you suggested and its worked out well - Thanks!

`{types: { friendsByAge: 'L' }}`

I've also added `preserveArrays()` to always consider arrays as `L`.
